class XlsxService
  def self.export_to_xlsx(params)
    result = SearchService.search(params)

    filename = params[:name].present? ? params[:name].gsub(' ', '_') : "Lista-#{Time.now.strftime("%d%m%Y%H%M")}.xlsx"
    workbook = WriteXLSX.new("/tmp/#{filename}")
    worksheet = workbook.add_worksheet
    
    format_headers = workbook.add_format
    format_headers.set_bold
    format_headers.set_color('black')
    format_headers.set_align('center')

    format_col = workbook.add_format
    format_col.set_align('center')

    date_format = workbook.add_format(num_format: 'dd/mm/yy')

    worksheet.set_column(0, 0, 55)
    worksheet.set_column(1, 1, 15)
    worksheet.set_column(2, 2, 40)
    worksheet.set_column(3, 3, 30)
    worksheet.set_column(4, 4, 30)
    worksheet.set_column(5, 5, 20)
    worksheet.set_column(6, 6, 15)
    worksheet.set_column(7, 7, 15)
    worksheet.set_column(8, 8, 15)
    worksheet.set_column(9, 9, 15)
    worksheet.set_column(10, 10, 15)
    worksheet.set_column(11, 11, 25)
    worksheet.set_column(12, 12, 130)
    worksheet.set_column(13, 13, 25)
    worksheet.set_column(14, 14, 15)
    worksheet.set_column(15, 15, 15)
    worksheet.set_column(16, 16, 15)
    worksheet.set_column(17, 17, 15)
    worksheet.set_column(18, 18, 15)
    worksheet.set_column(19, 19, 15)
    worksheet.set_column(20, 20, 15)
    worksheet.set_column(21, 21, 15)
    worksheet.set_column(22, 22, 15)
    worksheet.set_column(23, 23, 15)
    worksheet.set_column(24, 24, 15)
    worksheet.set_column(25, 25, 15)
    worksheet.set_column(26, 26, 15)
    worksheet.set_column(27, 27, 15)
    worksheet.set_column(28, 28, 15)
    worksheet.set_column(29, 29, 15)
    worksheet.set_column(30, 30, 15)
    worksheet.set_column(31, 31, 15)
    worksheet.set_column(32, 32, 15)
    worksheet.set_column(33, 33, 15)
    worksheet.set_column(34, 34, 15)
    worksheet.set_column(35, 35, 15)
    worksheet.set_column(36, 36, 15)
    worksheet.set_column(37, 37, 15)
    worksheet.set_column(38, 38, 15)
    worksheet.set_column(39, 39, 15)
    worksheet.set_column(40, 40, 15)
    worksheet.set_column(41, 41, 15)
    worksheet.set_column(42, 42, 15)

    worksheet.write(0, 0, "Razão Social", format_headers)
    worksheet.write(0, 1, "Telefone", format_headers)
    worksheet.write(0, 2, "E-mail", format_headers)
    worksheet.write(0, 3, "Pessoa de Contato", format_headers)
    worksheet.write(0, 4, "Observação", format_headers)
    worksheet.write(0, 5, "Data de Abertura", format_headers)
    worksheet.write(0, 6, "Situação", format_headers)
    worksheet.write(0, 7, "Motivo de Situação Cadastral", format_headers)
    worksheet.write(0, 8, "", format_headers)
    worksheet.write(0, 9, "", format_headers)
    worksheet.write(0, 10, "", format_headers)
    worksheet.write(0, 11, "Código Primario CNAE", format_headers)
    worksheet.write(0, 12, "Descrição Primario CNAE", format_headers)
    worksheet.write(0, 13, "Código Secundario CNAE", format_headers)
    worksheet.write(0, 14, "", format_headers)
    worksheet.write(0, 15, "", format_headers)
    worksheet.write(0, 16, "", format_headers)
    worksheet.write(0, 17, "", format_headers)
    worksheet.write(0, 18, "", format_headers)
    worksheet.write(0, 19, "", format_headers)
    worksheet.write(0, 20, "", format_headers)
    worksheet.write(0, 21, "", format_headers)
    worksheet.write(0, 22, "", format_headers)
    worksheet.write(0, 23, "", format_headers)
    worksheet.write(0, 24, "", format_headers)
    worksheet.write(0, 25, "", format_headers)
    worksheet.write(0, 26, "", format_headers)
    worksheet.write(0, 27, "", format_headers)
    worksheet.write(0, 28, "", format_headers)
    worksheet.write(0, 29, "", format_headers)
    worksheet.write(0, 30, "", format_headers)
    worksheet.write(0, 31, "", format_headers)
    worksheet.write(0, 32, "", format_headers)
    worksheet.write(0, 33, "", format_headers)
    worksheet.write(0, 34, "", format_headers)
    worksheet.write(0, 35, "", format_headers)
    worksheet.write(0, 36, "", format_headers)
    worksheet.write(0, 37, "", format_headers)
    worksheet.write(0, 38, "", format_headers)
    worksheet.write(0, 39, "", format_headers)
    worksheet.write(0, 40, "", format_headers)
    worksheet.write(0, 41, "", format_headers)
    worksheet.write(0, 42, "", format_headers)

    i = 1

    result[1].each do |re|
      worksheet.write(i, 0, re['fantasy_name'])
      worksheet.write(i, 1, "(#{re['telephone_one'][0, 2]}) #{re['telephone_one'][2, 4]}-#{re['telephone_one'][6, 4]}", format_col)
      worksheet.write(i, 2, re['email'])
      worksheet.write(i, 3, '')
      worksheet.write(i, 4, '')
      worksheet.write(i, 5, re['date_status_registration'] == '0' ? '-' : Date.strptime(re['date_status_registration'], "%Y%m%d").strftime("%d/%m/%Y"), format_col)
      worksheet.write(i, 6, re['registration_situation'], format_col)
      worksheet.write(i, 7, re['reason_registration_status_code'], format_col)
      worksheet.write(i, 8, re['city_name_outside'], format_col)
      worksheet.write(i, 9, re['nation'], format_col)
      worksheet.write(i, 10, re['start_date_activity'] == '0' ? '-' : Date.strptime(re['start_date_activity'], "%Y%m%d").strftime("%d/%m/%Y"), format_col)
      worksheet.write(i, 11, re['primary_cnae_code'], format_col)
      worksheet.write(i, 12, re['primary_cnae_description'])
      worksheet.write(i, 13, re['secondary_cnae_code'], format_col)
      worksheet.write(i, 14, re['type_street_name'], format_col)
      worksheet.write(i, 15, re['number'], format_col)
      worksheet.write(i, 16, re['complement'], format_col)
      worksheet.write(i, 17, re['district'], format_col)
      worksheet.write(i, 18, re['cep'], format_col)
      worksheet.write(i, 19, re['county_code'], format_col)
      worksheet.write(i, 20, re['county_description'], format_col)
      worksheet.write(i, 21, re['uf'], format_col)
      worksheet.write(i, 22, re['ddd_one'], format_col)
      worksheet.write(i, 23, re['telephone_one'], format_col)
      worksheet.write(i, 24, re['ddd_two'], format_col)
      worksheet.write(i, 25, re['telephone_two'], format_col)
      worksheet.write(i, 26, re['ddd_fax'], format_col)
      worksheet.write(i, 27, re['fax'], format_col)
      worksheet.write(i, 28, re['email'], format_col)
      worksheet.write(i, 29, re['special_situation'], format_col)
      worksheet.write(i, 30, re['date_special_situation'], format_col)
      worksheet.write(i, 31, re['simple_option'], format_col)
      worksheet.write(i, 32, re['date_option_simple'], format_col)
      worksheet.write(i, 33, re['date_exclusion_simple'], format_col)
      worksheet.write(i, 34, re['opting_for_mei'], format_col)
      worksheet.write(i, 35, re['mei_option_date'], format_col)
      worksheet.write(i, 36, re['date_exclusion_mei'], format_col)
      worksheet.write(i, 37, re['partners'], format_col)
      worksheet.write(i, 38, re['legal_nature'], format_col)
      worksheet.write(i, 39, re['qualification_responsible'], format_col)
      worksheet.write(i, 40, re['share_capital'], format_col)
      worksheet.write(i, 41, re['company_size_code'], format_col)
      worksheet.write(i, 42, re['federative_entity_responsible'], format_col)
      i += 1
    end

    workbook.close

    file = filename
  end
end