default: &default
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  adapter: postgresql
  database: db_desenv
  username: scm_minera_admin
  password: scm_minera_admin
  host: localhost
  port: 5432

development:
  <<: *default
  schema_search_path: scm_minera_customer